In [ ]:
#An example of the classes in python:
class Person:
    institution ="MSIS"
    def __init__(self, name, age,location):
        self.name = name
        self.age = age
        self.location =  location

    def set_name(self, name):
        self.name = name
    def get_name(self):
        return self.name
    def set_age(self, age):
        self.age = age
    def get_age(self):
        return self.age
    def set_location(self, location):
        self.location = location
    def get_location(self):
        return self.location


In [ ]:

initialize_name = Person("John", 36,'manipal')
get_name = initialize_name.get_name()
print(get_name)
set_name = initialize_name.set_name("Sheethal Doe")
get_name = initialize_name.get_name()
print(get_name)
get_loacation = initialize_name.get_location()
print(get_loacation)

John
Sheethal Doe
manipal


In [ ]:
print("this is where I work {}".format(initialize_name.get_location()))

this is where I workmanipal


In [ ]:
#@exampl
x={1,'x',2,'y',(1,2,3),'hello'}
y=(1,2,3)
type(x)
type(y)

tuple

In [ ]:
#sets are unorderd while printing order changes
y={'one','two','three'}
z={'three','two','one'}
print(y,z)

{'one', 'three', 'two'} {'one', 'three', 'two'}


In [ ]:
#add the value to the set
y.add(4)
z.add('a')
print(y,z)
print(y)

{'one', 'three', 4, 'two'} {'one', 'a', 'three', 'two'}
{'one', 'three', 4, 'two'}


In [ ]:
x=[1,'x',2,'y']
type(x)

list

In [ ]:
#here's an example of mapping the min function B/W thee list. Milk,  water,suger
store1=[10.00,11.00,12.89,33.00]
store2=[10.00,1.00,12.89,53.00]
store3=[110.00,131.00,152.89,3.00]
cheapst=map (min,store1,store2,store3)
COSTLY =map(max,store1, store2,store3)

print(cheapst)
print(list(cheapst))
print(COSTLY)
print(list(COSTLY))

[10.0, 1.0, 12.89, 3.0]
[110.0, 131.0, 152.89, 53.0]


In [ ]:
def calulatesquare(n):
  return n*n

In [ ]:
number=(1,2,3,4,5,6,7,8,9)
result=map(calulatesquare,number)
print(result)
for i in result:
  print(i)

1
4
9
16
25
36
49
64
81


In [ ]:
number=(1,2,3,4,5,6)
for i in map(lambda x:x*x,number):
  print(i)

1
4
9
16
25
36


In [ ]:
#lambda function
num1=[1,2,3]
num2=[4,5,6]
result=map(lambda n1,n2:n1+n2,num1,num2)
print(list(result))

[5, 7, 9]


In [ ]:
people= ['python programming language','computer lab test' ,'vinod scored a ','kumar is funny']
def split_title_and_name(person):
  title=person.split()[0]
  lastname=person.split()[-1]
  return '{} {}'.format(title,lastname)
list(map(split_title_and_name,people))

['python language', 'computer test', 'vinod a', 'kumar funny']

In [ ]:
dx= lambda x:x*2
print(dx(500))

1000


In [ ]:
dx =lambda x,y:(x+y)*2
print(dx(5,6))

22


In [ ]:
mylsi=[1,2,3,4,5,6,7,8,9]
new_list = map(lambda x:x**2,mylsi)
new_list1 = map(lambda x:x*2,mylsi)
for i in new_list:
  print(i)
print(end="\n\n\n\n\n")
for i in new_list1:
  print(i)

1
4
9
16
25
36
49
64
81





2
4
6
8
10
12
14
16
18


In [ ]:
#numpy
import numpy as np
my_lsit=[1,3,4,54,6,7,78,7]
print(my_lsit)
arr=np.array(my_lsit)
print(arr)
arr1=np.array([1,2,3,"dfsafsd"])
print(arr1)

[1, 3, 4, 54, 6, 7, 78, 7]
[ 1  3  4 54  6  7 78  7]
['1' '2' '3' 'dfsafsd']


In [ ]:
arr2=np.array([[1,2,3,"dfsafsd",9],[11,2,3,4,4]])

print(arr2)
print(arr2.shape)

[['1' '2' '3' 'dfsafsd' '9']
 ['11' '2' '3' '4' '4']]
(2, 5)


In [ ]:
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
# Assuming you want to reshape the array 'n' from the previous cell
n = np.reshape(n, (5, 3))
n

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [ ]:
lspace =np.linspace(0,10,9)
lspace

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
lspace.reshape(3,3)

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

In [ ]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
matrix1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
matrix2 = np.matrix([['4','d',3],[4,5,6],[7,8,9]])
print(matrix2)

[['4' 'd' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [ ]:
print('main Diagonal element: ',np.diag(matrix1))
print(' Diagonal element above main diagonal: ',np.diag(matrix1,1))
print(' Diagonal element below main diagonal: ',np.diag(matrix1,-1))

print(' Diagonal element one step above main diagonal: ',np.diag(matrix1,2))
print(' Diagonal element one step below main diagonal: ',np.diag(matrix1,-2))

main Diagonal element:  [1 5 9]
 Diagonal element above main diagonal:  [2 6]
 Diagonal element below main diagonal:  [4 8]
 Diagonal element one step above main diagonal:  [3]
 Diagonal element one step below main diagonal:  [7]


In [ ]:
p =np.array([1,2,3,4,5]*2)
p

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [ ]:
np.repeat([1,2,3,4,5],2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [ ]:
#combining arays
p=np.ones([3,3],int)

In [ ]:
np.vstack([p,2*p])

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10,  2,  4,  6,  8, 10]])

In [ ]:
np.hstack([2*p,p])

array([ 2,  4,  6,  8, 10,  2,  4,  6,  8, 10,  1,  2,  3,  4,  5,  1,  2,
        3,  4,  5])

In [ ]:
np.hstack([p,2*p,3*p])

array([ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  2,  4,  6,  8, 10,  2,  4,
        6,  8, 10,  3,  6,  9, 12, 15,  3,  6,  9, 12, 15])

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x)
print(y)

[1 2 3]
[4 5 6]


In [ ]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
x.dot(y)

np.int64(32)

In [ ]:
z=np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [ ]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [ ]:
print(z.dtype)
print(z.shape)
print(z.T.shape)

int64
(2, 3)
(3, 2)


In [ ]:
a= np.array([-4,-5,-6,-6,7,8,8])
print(a.sum())
print(a.max())
print(a.min())
print(a.mean())
print(a.std())

2
8
-6
0.2857142857142857
6.430158534243942
