In [2]:
# Core libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
# Preprocessing
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

# Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression, LinearRegression

# Evaluation
from sklearn.metrics import accuracy_score, confusion_matrix


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd
data = pd.read_csv("drive/My Drive/Colab Notebooks/Datasets/Social_Network_Ads.csv")
dataset = data
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
dataset.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [ ]:
#split independent variable

dataset
X = dataset.iloc[:, 1:4].values
X

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [ ]:
#Split dependent variable
y = dataset.iloc[:, -1].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X)


[[1 1 19000]
 [1 17 20000]
 [0 8 43000]
 ...
 [0 32 20000]
 [1 18 33000]
 [0 31 36000]]


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Different test sizes to check
test_sizes = [0.2, 0.25, 0.3]


In [ ]:
print("\n--- Decision Tree Confusion Matrices ---")
dt_conf_matrices = []
for ts in test_sizes:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=ts, random_state=0)

    dt = DecisionTreeClassifier(criterion='gini', random_state=0)
    dt.fit(X_train, y_train)
    y_pred_dt = dt.predict(X_test)

    cm = confusion_matrix(y_test, y_pred_dt)
    dt_conf_matrices.append(cm)

    print(f"Test size = {ts}:\n{cm}")


--- Decision Tree Confusion Matrices ---
Test size = 0.2:
[[53  5]
 [ 3 19]]
Test size = 0.25:
[[63  5]
 [ 4 28]]
Test size = 0.3:
[[71  8]
 [ 6 35]]


In [ ]:
print("\n--- Logistic Regression Confusion Matrices ---")
log_conf_matrices = []
for ts in test_sizes:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=ts, random_state=0)

    sc_X = StandardScaler()
    X_train = sc_X.fit_transform(X_train)
    X_test = sc_X.transform(X_test)

    log = LogisticRegression(random_state=0)
    log.fit(X_train, y_train)
    y_pred_log = log.predict(X_test)

    cm = confusion_matrix(y_test, y_pred_log)
    log_conf_matrices.append(cm)

    print(f"Test size = {ts}:\n{cm}")


--- Logistic Regression Confusion Matrices ---
Test size = 0.2:
[[56  2]
 [ 5 17]]
Test size = 0.25:
[[65  3]
 [ 7 25]]
Test size = 0.3:
[[74  5]
 [ 8 33]]


In [ ]:
print("\n--- Linear Regression Confusion Matrices ---")
lin_conf_matrices = []
for ts in test_sizes:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=ts, random_state=0)

    sc_X = StandardScaler()
    X_train = sc_X.fit_transform(X_train)
    X_test = sc_X.transform(X_test)

    lin = LinearRegression()
    lin.fit(X_train, y_train)
    y_pred_lin = lin.predict(X_test)

    # Convert to 0 or 1
    y_pred_lin_class = [1 if pred >= 0.5 else 0 for pred in y_pred_lin]

    cm = confusion_matrix(y_test, y_pred_lin_class)
    lin_conf_matrices.append(cm)

    print(f"Test size = {ts}:\n{cm}")


--- Linear Regression Confusion Matrices ---
Test size = 0.2:
[[57  1]
 [ 5 17]]
Test size = 0.25:
[[65  3]
 [ 8 24]]
Test size = 0.3:
[[74  5]
 [10 31]]


In [ ]:
print("\n--- Decision Tree Accuracy ---")
for ts, cm in zip(test_sizes, dt_conf_matrices):
    acc = (cm[0,0] + cm[1,1]) / cm.sum()   # Accuracy = (TP+TN)/Total
    print(f"Test size = {ts}, Accuracy = {acc}")


--- Decision Tree Accuracy ---
Test size = 0.2, Accuracy = 0.9
Test size = 0.25, Accuracy = 0.91
Test size = 0.3, Accuracy = 0.8833333333333333


In [ ]:
print("\n--- Logistic Regression Accuracy ---")
for ts, cm in zip(test_sizes, log_conf_matrices):
    acc = (cm[0,0] + cm[1,1]) / cm.sum()
    print(f"Test size = {ts}, Accuracy = {acc}")


--- Logistic Regression Accuracy ---
Test size = 0.2, Accuracy = 0.9125
Test size = 0.25, Accuracy = 0.9
Test size = 0.3, Accuracy = 0.8916666666666667


In [ ]:
print("\n--- Linear Regression Accuracy ---")
for ts, cm in zip(test_sizes, lin_conf_matrices):
    acc = (cm[0,0] + cm[1,1]) / cm.sum()
    print(f"Test size = {ts}, Accuracy = {acc}")


--- Linear Regression Accuracy ---
Test size = 0.2, Accuracy = 0.925
Test size = 0.25, Accuracy = 0.89
Test size = 0.3, Accuracy = 0.875


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[63,  5],
       [ 4, 28]])

In [ ]:
Accuracy = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[0][1]+cm[1][0]+cm[1][1])
Accuracy

np.float64(0.91)