In [56]:
#Logiostic Regression

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier

In [41]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [48]:
import pandas as pd
data = pd.read_csv("drive/My Drive/Colab Notebooks/Datasets/mushrooms.csv")
dataset = data
dataset

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [65]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()

for col in dataset.columns:
    dataset[col] = labelencoder.fit_transform(dataset[col])

print(dataset)

      class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                 

In [66]:
#split independent variable

dataset
X = dataset.iloc[:, 1:22].values
X

array([[5, 2, 4, ..., 4, 2, 3],
       [5, 2, 9, ..., 4, 3, 2],
       [0, 2, 8, ..., 4, 3, 2],
       ...,
       [2, 2, 4, ..., 4, 0, 1],
       [3, 3, 4, ..., 0, 7, 4],
       [5, 2, 4, ..., 4, 4, 1]])

In [67]:
#Split dependent variable
y = dataset.iloc[:, -1].values
y

array([5, 1, 3, ..., 2, 2, 2])

In [69]:
#Split data into Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)


In [70]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [71]:
model = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
AdaBoost = AdaBoostClassifier(estimator=model, n_estimators=400, learning_rate=1, random_state=0)
boostmodel = AdaBoost.fit(X_train, y_train)



In [72]:
y_pred = boostmodel.predict(X_test)
y_pred

array([1, 0, 3, ..., 4, 1, 2])

In [73]:
y_test

array([5, 0, 3, ..., 0, 1, 2])

In [74]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[539,  35,  43,   0, 175,   0,   0],
       [ 65, 278,   0,  75,  49,  59,   0],
       [ 98,   0,  74,   0,  36,   0,   0],
       [  0,  72,   0,   8,   0,   0,   0],
       [ 91,  81, 110,   0,  15,   0,   0],
       [  0,  58,   0,   0,   0,  31,   0],
       [  0,   0,   0,   0,   0,   0,  39]])

In [75]:
Accurancy = (cm[0][0]+cm[1][1])/(cm[0][0]+cm[0][1]+cm[1][0]+cm[1][1])
Accurancy

np.float64(0.8909487459105779)

In [76]:
from sklearn import metrics
prediction = metrics.accuracy_score(y_test, y_pred)
print("Accuracy", prediction *100, '%')

Accuracy 48.44903988183161 %


In [82]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.68      0.68      0.68       792
           1       0.53      0.53      0.53       526
           2       0.33      0.36      0.34       208
           3       0.10      0.10      0.10        80
           4       0.05      0.05      0.05       297
           5       0.34      0.35      0.35        89
           6       1.00      1.00      1.00        39

    accuracy                           0.48      2031
   macro avg       0.43      0.44      0.44      2031
weighted avg       0.48      0.48      0.48      2031

