Data Preprocessingt steps

1.Importing the libraries

2.Importing the dataset

3.Taking care of missing Data

4.Encoding categorical Data

5.Encoding the Independent Variable

6.Encoding the Dependent Variable

7.Train-Test Split

8.Feature Scaling

In [64]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [69]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [70]:
import pandas as pd
data = pd.read_csv("drive/My Drive/Colab Notebooks/Datasets/DataOLD.csv")
dataset = data
dataset

Country   Age   Salary Purchased
0   France   NaN      NaN        No
1    Spain  27.0  48000.0       Yes
2  Germany   NaN  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0      NaN       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [71]:
#split independent variable

dataset
X = dataset.iloc[:, :-1].values
X

array([['France', nan, nan],
       ['Spain', 27.0, 48000.0],
       ['Germany', nan, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, nan],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [72]:
#Split dependent variable
y = dataset.iloc[:, 3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [73]:
#Taking care of missing values

#fill the "Nan" with mean of all the values
#assignment - most occuring number to fit in the "Nan"

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, 1:3]) #imputer is a class
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

array([['France', 39.285714285714285, 60428.57142857143],
       ['Spain', 27.0, 48000.0],
       ['Germany', 39.285714285714285, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 60428.57142857143],
       ['France', 35.0, 58000.0],
       ['Spain', 39.285714285714285, 52000.0],
       ['France', 48.0, 60428.57142857143],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [74]:
#Encoding the Categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X)

[[0 39.285714285714285 60428.57142857143]
 [2 27.0 48000.0]
 [1 39.285714285714285 54000.0]
 [2 38.0 61000.0]
 [1 40.0 60428.57142857143]
 [0 35.0 58000.0]
 [2 39.285714285714285 52000.0]
 [0 48.0 60428.57142857143]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [75]:
#Encoding the Independent Variable

from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(),[0])], remainder="passthrough")
X = ct.fit_transform(X)
X.astype(int)

array([[    1,     0,     0,    39, 60428],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    39, 54000],
       [    0,     0,     1,    38, 61000],
       [    0,     1,     0,    40, 60428],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    39, 52000],
       [    1,     0,     0,    48, 60428],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [76]:
#Encoding the Dependent Variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [78]:
#Split data into Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)


In [84]:
dataset.shape

(10, 4)

In [85]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        7 non-null      float64
 2   Salary     7 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [86]:
dataset.describe()

Age        Salary
count   7.000000      7.000000
mean   39.285714  60428.571429
std     7.825477  11731.114509
min    27.000000  48000.000000
25%    36.000000  53000.000000
50%    38.000000  58000.000000
75%    44.000000  64000.000000
max    50.000000  83000.000000

In [79]:
#X_train.astype(int)
X_test

array([[0.0, 1.0, 0.0, 39.285714285714285, 54000.0],
       [0.0, 1.0, 0.0, 40.0, 60428.57142857143]], dtype=object)

In [81]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [82]:
X_test

array([[-1.        ,  2.64575131, -0.77459667,  0.013185  , -0.73279316],
       [-1.        ,  2.64575131, -0.77459667,  0.11866496, -0.08142146]])

In [83]:
X_train

array([[-1.        , -0.37796447,  1.29099445, -1.80107041, -1.34074007],
       [-1.        ,  2.64575131, -0.77459667,  1.59538447,  2.20561693],
       [ 1.        , -0.37796447, -0.77459667, -0.32435089,  0.58442516],
       [-1.        , -0.37796447,  1.29099445,  0.013185  , -0.93544213],
       [ 1.        , -0.37796447, -0.77459667, -0.6196948 , -0.32749521],
       [ 1.        , -0.37796447, -0.77459667,  1.30004057, -0.08142146],
       [ 1.        , -0.37796447, -0.77459667,  0.013185  , -0.08142146],
       [-1.        , -0.37796447,  1.29099445, -0.17667894, -0.02352176]])